# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# This file should contain a [[items]] section for each application you want themed
# You can also set a shell (outside items) on which to run hooks
# Check flavours repository for more information and examples

shell = "bash -c '{}'"

[[items]]
file = "~/dotfiles/waybar/colors.css"
rewrite = true
template = "waybar"

[[items]]
file = "~/.config/alacritty/alacritty.toml"
subtemplate = "default-256"
start = "# start flavours"
end = "# end flavours"
template = "alacritty"
 
[[items]]
file = "~/.config/nvim/lua/plugins/mini-base16.lua"
start = "-- start flavours"
end = "-- end flavours"
template = "nvim"

