shell = "/usr/bin/zsh"

[window]
padding = { x = 5, y = 10 }
opacity = 0.95
blur = true

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 12

[colors.primary]
foreground = "#121212"
background = "#fafafa"

